name: Build Python App for Linux

on:
  push:
    branches:
      - main  # Trigger on push to main branch (can be changed to your target branch)

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Use the version of Python you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run build.sh
      run: |
        chmod +x build.sh  # Make sure build.sh is executable
        ./build.sh  # Run the build script that uses pyinstaller to create the executable

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-executable  # Name of the artifact (will be shown in the Actions tab)
        path: dist/your_executable  # Path to your final executable after pyinstaller build

    - name: Print download link
      run: |
        echo "Download your app from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
