name: Build Python App for Fedora Linux

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Default runner to start the job
    container:  # Use a Fedora container
      image: fedora:latest  # Latest Fedora image

    steps:
    - name: Update Fedora and install Python
      run: |
        dnf update -y
        dnf install -y python3 python3-pip git binutils  # Install Python and binutils for objdump

    - name: Verify objdump installation
      run: |
        objdump --version  # Confirm that objdump is available

    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the repository  # Debugging step to list the files
      run: ls -al  # This will print the file structure

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run build.sh
      run: |
        chmod +x build.sh  # Make sure build.sh is executable
        ./build.sh  # Run the build script that uses pyinstaller to create the executable

    - name: List files in dist/
      run: |
        ls -al dist/  # Confirm the dist directory contains the built executables

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: fedora-linux-executable
        path: |
          dist/tkforge-cli
          dist/TkForge

    - name: Print download link
      run: |
        echo "Download your app from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
